[package]
name = "lldap_opaque_legacy"
version = "0.1.0"
description = "Verification of LLDAP 0.6.x OPAQUE password files and server keys for migration"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
digest = "0.9"
generic-array = "0.14"
opaque-ke-legacy = { package = "opaque-ke", version = "0.7.0" }
curve25519-dalek = "3"
rand = { workspace = true }
rust-argon2 = "2"
sha2 = "0.9"

[dev-dependencies]
pretty_assertions = { workspace = true }
rand_chacha = "0.3"

[dev-dependencies.lldap_auth]
path = "../auth"
features = ["opaque_server", "opaque_client"]
