[package]
name = "lldap_keycloak"
version = "0.1.0"
description = "Keycloak federation client and settings for KLLDAP"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
toml = "0.8"
tracing = { workspace = true }

[dependencies.lldap_domain_handlers]
path = "../domain-handlers"
